# ---------------------------------------------------------------------------
# AUTO-GENERATED BY SQLACODEGEN - DO NOT EDIT
# ---------------------------------------------------------------------------

from typing import Optional
import datetime

from sqlalchemy import Column, DateTime, Index, Integer, PrimaryKeyConstraint, String, Text, text
from sqlalchemy.dialects.postgresql import TIMESTAMP
from sqlmodel import Field, SQLModel

class PrismaMigrations(SQLModel, table=True):
    __tablename__ = '_prisma_migrations'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='_prisma_migrations_pkey'),
    )

    id: str = Field(sa_column=Column('id', String(36), primary_key=True))
    checksum: str = Field(sa_column=Column('checksum', String(64), nullable=False))
    migration_name: str = Field(sa_column=Column('migration_name', String(255), nullable=False))
    started_at: datetime.datetime = Field(sa_column=Column('started_at', DateTime(True), nullable=False, server_default=text('now()')))
    applied_steps_count: int = Field(sa_column=Column('applied_steps_count', Integer, nullable=False, server_default=text('0')))
    finished_at: Optional[datetime.datetime] = Field(default=None, sa_column=Column('finished_at', DateTime(True)))
    logs: Optional[str] = Field(default=None, sa_column=Column('logs', Text))
    rolled_back_at: Optional[datetime.datetime] = Field(default=None, sa_column=Column('rolled_back_at', DateTime(True)))


class DailyUsageEvents(SQLModel, table=True):
    __tablename__ = 'daily_usage_events'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='daily_usage_events_pkey'),
    )

    id: int = Field(sa_column=Column('id', Integer, primary_key=True))
    user_id: int = Field(sa_column=Column('user_id', Integer, nullable=False))
    date_key: str = Field(sa_column=Column('date_key', String(10), nullable=False))
    request_id: str = Field(sa_column=Column('request_id', String(64), nullable=False))
    status: str = Field(sa_column=Column('status', String(16), nullable=False))
    reserved_at: datetime.datetime = Field(sa_column=Column('reserved_at', TIMESTAMP(precision=3), nullable=False, server_default=text('CURRENT_TIMESTAMP')))
    created_at: datetime.datetime = Field(sa_column=Column('created_at', TIMESTAMP(precision=3), nullable=False, server_default=text('CURRENT_TIMESTAMP')))
    committed_at: Optional[datetime.datetime] = Field(default=None, sa_column=Column('committed_at', TIMESTAMP(precision=3)))


class Users(SQLModel, table=True):
    __table_args__ = (
        PrimaryKeyConstraint('id', name='users_pkey'),
        Index('users_email_key', 'email', unique=True)
    )

    id: int = Field(sa_column=Column('id', Integer, primary_key=True))
    email: str = Field(sa_column=Column('email', Text, nullable=False))
    plan_tier: str = Field(sa_column=Column('plan_tier', String(16), nullable=False, server_default=text("'starter'::character varying")))
    created_at: datetime.datetime = Field(sa_column=Column('created_at', TIMESTAMP(precision=3), nullable=False, server_default=text('CURRENT_TIMESTAMP')))
    name: Optional[str] = Field(default=None, sa_column=Column('name', Text))
